[tool.poetry]
name = "ecg-arr"
version = "0.1.0"
description = "Perform AI-based ECG arrhythmia classification"
authors = ["Adam Page <apage224@gmail.com>"]

[tool.poetry.dependencies]
python = ">=3.8,<3.11"
tensorflow-macos = {version = "^2.9.2", platform = "darwin"}
tensorflow = {version = "^2.9.1", platform = "!darwin"}
numpy = "^1.23.0"
scipy = "^1.8.1"
scikit-learn = "^1.1.1"
wfdb = "^4.0.0"
tensorflow-metal = {version = "^0.5.0", platform = "darwin"}
fastparquet = "^0.8.1"
plotly = "^5.9.0"
tqdm = "^4.64.0"
wandb = "^0.13.1"

[tool.poetry.dev-dependencies]
ipython = "^8.4.0"
jupyter = "^1.0.0"
jupyterlab = "^3.4.3"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
