[tool.poetry]
name = "ecg-arr"
version = "0.1.0"
description = "Perform AI-based ECG arrhythmia classification"
authors = ["Adam Page <adam.page@ambiq.com>"]

[tool.taskipy.tasks]
lint = "pylint --rcfile .pylintrc ecgarr"
test = "pytest tests/"

[tool.poetry.dependencies]
python = ">=3.9,<3.11"
tensorflow-macos = {version = "^2.10.0", platform = "darwin"}
tensorflow = {version = "^2.10.0", platform = "linux"}
numpy = "^1.23.0"
scipy = "^1.9.1"
scikit-learn = "^1.1.1"
wfdb = "^4.0.0"
tensorflow-metal = {version = "^0.6.0", platform = "darwin"}
fastparquet = "^0.8.1"
plotly = "^5.9.0"
tqdm = "^4.64.0"
wandb = "^0.13.1"
seaborn = "^0.11.2"
neurokit2 = "^0.2.0"
tensorflow-model-optimization = "^0.7.3"
pydantic = "^1.10.2"
pydantic-argparse = "^0.5.0"
pylint = "^2.15.2"
typer = {version = "^0.6.1", extras = ["all"]}

[tool.poetry.dev-dependencies]
ipython = "^8.4.0"
jupyter = "^1.0.0"
jupyterlab = "^3.4.3"
pytest = "^7.1.3"
taskipy = "^1.10.3"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
