[tool.poetry]
name = "ecg-arr"
version = "0.1.0"
description = "Perform AI-based heart arrhythmia classification"
authors = ["Adam Page <adam.page@ambiq.com>"]

[tool.taskipy.tasks]
black = "black ecgarr"
lint = "pylint ecgarr"
test = "pytest tests/"
clean = "make -C ./evb clean"
build = "make -C ./evb"

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-ra -q"
testpaths = [
    "tests",
]
filterwarnings = [
    "ignore:Call to deprecated create:DeprecationWarning",
    "ignore:distutils Version:DeprecationWarning",
    "ignore:The register_cmap function:PendingDeprecationWarning"
]

[tool.poetry.dependencies]
python = ">=3.9,<3.11"
tensorflow-macos = {version = "^2.10.0", platform = "darwin"}
tensorflow = {version = "^2.10.0", platform = "linux"}
numpy = "^1.23.0"
scikit-learn = "^1.1.1"
wfdb = "^4.0.0"
tensorflow-metal = {version = "^0.6.0", platform = "darwin"}
fastparquet = "^0.8.1"
plotly = "^5.9.0"
tqdm = "^4.64.0"
seaborn = "^0.11.2"
neurokit2 = "^0.2.0"
tensorflow-model-optimization = "^0.7.3"
pydantic = "^1.10.2"
pydantic-argparse = "^0.5.0"
pylint = "^2.15.2"
typer = {version = "^0.6.1", extras = ["all"]}
erpc = {git = "https://github.com/AmbiqAI/erpc.git", rev = "develop", subdirectory = "erpc_python"}
pyserial = "^3.5"
rich = "^12.5.1"
wandb = "0.13.4"
tensorflow-addons = "^0.18.0"
scipy = "^1.9.1"
plotext = "^5.2.7"

[tool.poetry.group.dev.dependencies]
black = "^22.8.0"
ipython = "^8.4.0"
pytest = "^7.1.3"
taskipy = "^1.10.3"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.isort]
profile = 'black'

[tool.pylint.master]
ignore-paths = [
    "ecgarr/rpc/GenericDataOperations_EvbToPc",
    "ecgarr/rpc/GenericDataOperations_PcToEvb",
    "ecgarr/models"
]
extension-pkg-whitelist = "pydantic"

[tool.pylint.message_control]
disable = [
    "unused-argument",
    "missing-module-docstring",
    "too-few-public-methods",
    "invalid-name",
    "logging-fstring-interpolation",
    "duplicate-code"
]

[tool.pylint.format]
max-line-length = 140

[tool.pylint.design]
max-args = 10
max-locals = 30
max-statements = 80
max-module-lines = 2000
max-attributes = 10
